[package]
name = "display_project"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
minifb = "0.27.0"
rand = "0.9.0-beta.1"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
